### ISSUE TITLE
Bug: source connector batch size bug results in uncommitted offsets

### ISSUE THREAD

**Issue by rauanmayemir** [ConduitIO/conduit-connector-kafka#220]
### Bug description

If a kafka topic doesn't see much traffic, source connector will never commit offsets until the batch size of 1000 is fulfilled. 

### Steps to reproduce

We need to set up a source connector:

```
- id: source-redpanda
  type: source
  plugin: builtin:kafka
  settings:
    servers: "..."
    topics: outbox.events
    groupID: 'cnd-outbox-group-id-1'
    readFromBeginning: 'true'
    retryGroupJoinErrors: 'true'
    saslMechanism: 'SCRAM-SHA-256'
    saslUsername: 'cnd_client'
    saslPassword: ${KAFKA_AUTH_PASSWORD}
    sdk.schema.extract.key.enabled: 'false'
    sdk.schema.extract.payload.enabled: 'false
```

Start producing messages. When the messages count reachs 1000, it will be committed.
But if we don't reach >2000 after that, messages are consumed but offset will never move, so we will always have a consumer lag.

### Version

v0.13.4
